##############################################################
#                                                            #
#                                                            #
#                     Coded by crashsystem!                  #
#                                                            #
#                                                            #
##############################################################
# Включить/выключить команду
command-enabled: true

# Название команды
command-name: vaip

# Кд команды в секундах
cooldown-seconds: 3600 # 1 час

# Команда, которая будет после прописывание /vaip писать без /
executed-command: kit pvp

# Команды этого плагина
# /cv reload перезагрузка конфига
# /cv true включить команду
# /cv false выключить команду
